    figure
    subplot(4, 2, 1)
    plot(spd_lconv_1_5, Vtke_lconv_1_5)
    xlabel('Wind Speed (m/s)')
    ylabel('V tke')
    title('1.5m')
    subplot(4, 2, 2)
    plot(spd_lconv_3, Vtke_lconv_3)
    xlabel('Wind Speed (m/s)')
    ylabel('V tke')
    title('3.0m')
    subplot(4, 2, 3)
    plot(spd_lconv_4_5, Vtke_lconv_4_5)
    xlabel('Wind Speed (m/s)')
    ylabel('V tke')
    title('4.5m')
    subplot(4, 2, 4)
    plot(spd_lconv_6, Vtke_lconv_6)
    xlabel('Wind Speed (m/s)')
    ylabel('V tke')
    title('6.0m')
    subplot(4, 2, 5)
    plot(spd_lconv_8_5, Vtke_lconv_8_5)
    xlabel('Wind Speed (m/s)')
    ylabel('V tke')
    title('8.5m')
    subplot(4, 2, 6)
    plot(spd_lconv_10, Vtke_lconv_10)
    xlabel('Wind Speed (m/s)')
    ylabel('V tke')
    title('10.0m')
    subplot(4, 2, 7)
    plot(spd_lconv_15, Vtke_lconv_15)
    xlabel('Wind Speed (m/s)')
    ylabel('V tke')
    title('15.0m')
    subplot(4, 2, 8)
    plot(spd_lconv_20, Vtke_lconv_20)
    xlabel('Wind Speed (m/s)')
    ylabel('V tke')
    title('20.0m')
    %set(gcf,'PaperSize',[40 20])
    print(gcf, strcat(targetDate, '_all_lconv'), '-dpdf','-fillpage');
